// <auto-generated />
namespace Labores.Context.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NuevosCampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NuevosCampos));
        
        string IMigrationMetadata.Id
        {
            get { return "201604071015137_NuevosCampos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
