// <auto-generated />
namespace Labores.Context.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CambioNombreTaablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambioNombreTaablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201604070929186_CambioNombreTaablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
